//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscuela.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        public alumno()
        {
            this.idiomas = new HashSet<idioma>();
        }
    
        public int id_alumno { get; set; }
        public string Nombre { get; set; }
        public int Matricula { get; set; }
        public int Matricula_idMatricula { get; set; }
    
        public virtual matricula matricula1 { get; set; }
        public virtual ICollection<idioma> idiomas { get; set; }
    }
}
