//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscuela.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class idioma
    {
        public idioma()
        {
            this.alumnoes = new HashSet<alumno>();
        }
    
        public int idIdiomas { get; set; }
        public string Nombre { get; set; }
        public string Nivel { get; set; }
    
        public virtual ICollection<alumno> alumnoes { get; set; }
    }
}
