//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscuela.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class matricula
    {
        public matricula()
        {
            this.alumnoes = new HashSet<alumno>();
            this.pagos = new HashSet<pago>();
        }
    
        public int idMatricula { get; set; }
        public Nullable<int> Numero_Contrato { get; set; }
        public string Estatus { get; set; }
        public Nullable<decimal> Costo_Total { get; set; }
        public Nullable<int> Cuota { get; set; }
        public Nullable<decimal> Importe_Mensual { get; set; }
        public Nullable<System.DateTime> Fecha_Matricula { get; set; }
        public Nullable<System.DateTime> Fecha_Validacion { get; set; }
        public Nullable<decimal> No_Puntos { get; set; }
        public Nullable<int> No_RP { get; set; }
        public string Tiempo_Servicio { get; set; }
        public string Tipo_Programa { get; set; }
        public string Estrategia { get; set; }
        public Nullable<int> No_Confidencial { get; set; }
        public Nullable<decimal> Saldo_Pendiente { get; set; }
        public int Organizacion_idOrganizacion { get; set; }
        public int Titular_idTitular { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> Vigencia { get; set; }
        public Nullable<int> No_Consecutivo { get; set; }
        public int Subgerente_idSubgerente { get; set; }
        public int Supervisor_idSupervisor { get; set; }
        public int Asesor_idAsesor { get; set; }
    
        public virtual ICollection<alumno> alumnoes { get; set; }
        public virtual asesor asesor { get; set; }
        public virtual organizacion organizacion { get; set; }
        public virtual subgerente subgerente { get; set; }
        public virtual supervisor supervisor { get; set; }
        public virtual titular titular { get; set; }
        public virtual ICollection<pago> pagos { get; set; }
    }
}
