//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscuela.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class multilingualEntities : DbContext
    {
        public multilingualEntities()
            : base("name=multilingualEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<alumno> alumnoes { get; set; }
        public DbSet<asesor> asesors { get; set; }
        public DbSet<dom_titular> dom_titular { get; set; }
        public DbSet<idioma> idiomas { get; set; }
        public DbSet<matricula> matriculas { get; set; }
        public DbSet<organizacion> organizacions { get; set; }
        public DbSet<pago> pagos { get; set; }
        public DbSet<subgerente> subgerentes { get; set; }
        public DbSet<supervisor> supervisors { get; set; }
        public DbSet<titular> titulars { get; set; }
    }
}
