//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscuela.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class organizacion
    {
        public organizacion()
        {
            this.asesors = new HashSet<asesor>();
            this.matriculas = new HashSet<matricula>();
            this.subgerentes = new HashSet<subgerente>();
            this.supervisors = new HashSet<supervisor>();
        }
    
        public int idOrganizacion { get; set; }
        public string Nombre { get; set; }
        public string Gerente { get; set; }
    
        public virtual ICollection<asesor> asesors { get; set; }
        public virtual ICollection<matricula> matriculas { get; set; }
        public virtual ICollection<subgerente> subgerentes { get; set; }
        public virtual ICollection<supervisor> supervisors { get; set; }
    }
}
